title: The LITzman outlet
email: talberliner111@ggmail..com
description: >-
baseurl: ""
url: "https://litzman.com"
twitter_username: TalB87268183
github_username:  LITzman

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "dark"
  back_home_text: ".."
  date_format: "%Y-%m-%d"